### ISSUE TITLE
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.clusterhack.ArgonOne': no such name

### ISSUE THREAD

**Issue by jimmyff** [spapadim/argon1#5]
Hey thanks for creating this, I just got it installed on ubuntu 20.04 but getting the following when i try to use it:

```
jimmyff@spritz:~$ argonctl speed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.clusterhack.ArgonOne': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/argonctl", line 11, in <module>
    load_entry_point('argon1==0.1', 'console_scripts', 'argonctl')()
  File "/usr/lib/python3/dist-packages/argonone/cmdline.py", line 150, in argonctl_main
    with dbus_proxy() as dbus:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/argonone/__init__.py", line 627, in dbus_proxy
    proxy = system_bus.get_object('net.clusterhack.ArgonOne',
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name net.clusterhack.ArgonOne was not provided by any .service files
```

**Comment by D4nielB** [comment]
Getting the same after a fresh install of Raspberry Pi OS and this tool. Found any solution?

Edit: Found the solution in another issue here: had to enable the I2C kernel module in raspi-config
